---

#############################################################################
# Provision hello-world
# This role executes much of the needed functionality to provision an
# application using an Ansible Playbook Bundle.  Included in the comments
# below are some sample resources for getting started deploying an application
# to OpenShift.
#############################################################################

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster

# These can always be overridden at the command line
# http://docs.ansible.com/ansible/devel/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
- name: 'Set facts'
  set_fact:
    cluster: '{{ "openshift" if "openshift" in lookup("k8s", cluster_info="version") else "kubernetes" }}'

- name: 'Set broker objects state={{ state }}'
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.apply | default(True)
  loop:
    - name: deployment.yml
    - name: service.yml
    - name: route.yml
      apply: "{{ True if cluster == 'openshift' else False }}"

- name: "Update last operation"
  asb_last_operation:
    description: "50%: Cluster objects state={{ state }}"
  when: in_cluster

- include_tasks: "verify_{{ apb_action }}.yml"

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Done"
  when: in_cluster
