#############################################################################
# Provision hello-world
# This role executes much of the needed functionality to provision an
# application using an Ansible Playbook Bundle.  Included in the comments
# below are some sample resources for getting started deploying an application
# to OpenShift.
#############################################################################

- name: load variables for {{ apb_action }}
  include_vars:
    file: '{{ apb_action }}.yml'

#############################################################################
# An OpenShift Origin deployment configuration provides a replication
# controller, spins up pods, and also provides the ability to transition from
# one deployment of an image to a new one.
# https://docs.openshift.org/latest/architecture/core_concepts/deployments.html#deployments-and-deployment-configurations
#############################################################################
- name: deployment config
  openshift_raw:
    state: '{{ state }}'
    definition: "{{ lookup('template', 'deployment_config.yml') | from_yaml }}"


#############################################################################
# A Kubernetes service serves as an internal load balancer.  It identifies a
# set of replicated pods in order to proxy the connections it receives to them.
# https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html#services
#############################################################################
- name: hello-world service
  k8s_raw:
    state: '{{ state }}'
    definition: "{{ lookup('template', 'service.yml') | from_yaml }}"


#############################################################################
# An OpenShift Origin route exposes a service at a host name, so that external
# clients can reach it by name. Each route consists of a name, a service
# selector, and an optional security configuration.
# https://docs.openshift.org/latest/architecture/core_concepts/routes.html
#############################################################################
- name: create hello-world route
  openshift_raw:
    state: '{{ state }}'
    definition: "{{ lookup('template', 'route.yml') | from_yaml }}"

