---
# Notice that the prefix was removed from route.openshift.io/v1
apiVersion: v1
kind: Route
metadata:
  labels:
    app: {{ app_name }}
    service: {{ app_name }}
  name: {{ app_name }}
  namespace: {{ namespace }}
spec:
  port:
    targetPort: web
  to:
    kind: Service
    name: {{ app_name }}
